# Generated by Django 5.1.1 on 2024-10-10 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='temp_videos/')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=500)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails')),
                ('location', models.URLField(default='http://localhost:8000/media/videos/', max_length=255)),
            ],
        ),
    ]
