# Generated by Django 5.1.1 on 2024-10-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('new', 'New on Videoflix'), ('documentary', 'Documentary'), ('drama', 'Drama'), ('romance', 'Romance')], default='New on Videoflix', max_length=16),
        ),
    ]
