# Generated by Django 5.1.1 on 2024-10-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_video_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('new', 'New on Videoflix'), ('documentary', 'Documentary'), ('drama', 'Drama'), ('romance', 'Romance')], default='new', max_length=16),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=16),
        ),
    ]
