# Generated by Django 5.1.1 on 2024-11-08 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_videoprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoprogress',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
